user alumina_backend
topic write aluminum/alarm/+
topic write aluminum/status/+
topic read aluminum/#

user alumina_dashboard
topic read aluminum/alarm/+
topic read aluminum/status/+

pattern read aluminum/status/%u
